### ISSUE TITLE
Persistent add_rule bug prevents running any commands

### ISSUE THREAD

**Issue by hhollandmoritz** [epruesse/ymp#79]
When I try to run any command other than the most basic, I get a persistent error that looks like the following: 
```
(ymp) [hannah@rgnt1-24-235-dhcp ymp]$ ymp stage list
Traceback (most recent call last):
  File "/home/hannah/Software/miniconda2/envs/ymp/bin/ymp", line 10, in <module>
    sys.exit(main())
  File "/home/hannah/Software/miniconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hannah/Software/miniconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hannah/Software/miniconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hannah/Software/miniconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hannah/Software/miniconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hannah/Software/miniconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hannah/Software/ymp/src/ymp/cli/stage.py", line 61, in ls
    stages = list(all_stages.values())
  File "/home/hannah/Software/ymp/src/ymp/common.py", line 305, in values
    self._loadall()
  File "/home/hannah/Software/ymp/src/ymp/common.py", line 243, in _loadall
    self._loadfunc(*self._args, **self._kwargs)
  File "/home/hannah/Software/ymp/src/ymp/snakemake.py", line 280, in ensure_global_workflow
    cls.load_workflow()
  File "/home/hannah/Software/ymp/src/ymp/snakemake.py", line 270, in load_workflow
    workflow.include(snakefile)
  File "/home/hannah/Software/miniconda2/envs/ymp/lib/python3.6/site-packages/snakemake/workflow.py", line 743, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/home/hannah/Software/ymp/src/ymp/rules/Snakefile", line 51, in <module>
    
  File "/home/hannah/Software/miniconda2/envs/ymp/lib/python3.6/site-packages/snakemake/workflow.py", line 743, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/home/hannah/Software/ymp/src/ymp/rules/00_download.rules", line 3, in <module>
    """
  File "/home/hannah/Software/ymp/src/ymp/snakemake.py", line 351, in rule
    decorator = super().rule(name, lineno, snakefile)
  File "/home/hannah/Software/miniconda2/envs/ymp/lib/python3.6/site-packages/snakemake/workflow.py", line 807, in rule
    name = self.add_rule(name, lineno, snakefile, checkpoint)
TypeError: add_rule() takes from 1 to 4 positional arguments but 5 were given
```
This also happens when running other commands such as ```ymp init demo```, ```ymp stage list```, or  ```ymp make```. Displaying the help printout for these commands always works.

I suspect it has something to do with the package environment. When searching through the issues I noticed one about snakemake version being important. So I tried forcing the snakemake version to be 5.2.2 exactly in the environment.yaml. Now I am able to get ```ymp stage list``` to work as expected but the add_rule error persists when running ```ymp make```. For example: 

```
(ymp) [hollandh@microbe ymp_demo]$ ymp make toy.assemble_megahit.map_bbmap
YMP: dropping cache
Traceback (most recent call last):
  File "/data/hollandh/anaconda2/envs/ymp/bin/ymp", line 10, in <module>
    sys.exit(main())
  File "/data/hollandh/anaconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/data/hollandh/anaconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/data/hollandh/anaconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/hollandh/anaconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/hollandh/anaconda2/envs/ymp/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/data/hollandh/ymp/src/ymp/cli/make.py", line 141, in decorated
    return func(*args, **kwargs)
  File "/data/hollandh/ymp/src/ymp/cli/make.py", line 248, in make
    rval = start_snakemake(kwargs)
  File "/data/hollandh/ymp/src/ymp/cli/make.py", line 205, in start_snakemake
    stack = StageStack.get(t)
  File "/data/hollandh/ymp/src/ymp/stage.py", line 55, in get
    return cache[path]
  File "/data/hollandh/ymp/src/ymp/common.py", line 271, in __getitem__
    self._loaditem(key)
  File "/data/hollandh/ymp/src/ymp/common.py", line 224, in _loaditem
    item = self._itemloadfunc(key)
  File "/data/hollandh/ymp/src/ymp/stage.py", line 83, in __init__
    stage = self._find_stage(top_stage)
  File "/data/hollandh/ymp/src/ymp/stage.py", line 145, in _find_stage
    for stage in registry.values():
  File "/data/hollandh/ymp/src/ymp/common.py", line 305, in values
    self._loadall()
  File "/data/hollandh/ymp/src/ymp/common.py", line 243, in _loadall
    self._loadfunc(*self._args, **self._kwargs)
  File "/data/hollandh/ymp/src/ymp/snakemake.py", line 280, in ensure_global_workflow
    cls.load_workflow()
  File "/data/hollandh/ymp/src/ymp/snakemake.py", line 270, in load_workflow
    workflow.include(snakefile)
  File "/data/hollandh/anaconda2/envs/ymp/lib/python3.6/site-packages/snakemake/workflow.py", line 743, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/data/hollandh/ymp/src/ymp/rules/Snakefile", line 51, in <module>
    
  File "/data/hollandh/anaconda2/envs/ymp/lib/python3.6/site-packages/snakemake/workflow.py", line 743, in include
    exec(compile(code, snakefile, "exec"), self.globals)
  File "/data/hollandh/ymp/src/ymp/rules/00_download.rules", line 3, in <module>
    """
  File "/data/hollandh/ymp/src/ymp/snakemake.py", line 351, in rule
    decorator = super().rule(name, lineno, snakefile)
  File "/data/hollandh/anaconda2/envs/ymp/lib/python3.6/site-packages/snakemake/workflow.py", line 807, in rule
    name = self.add_rule(name, lineno, snakefile, checkpoint)
TypeError: add_rule() takes from 1 to 4 positional arguments but 5 were given
```
Interestingly, now even after I restore snakemake 5.2.2 to 5.4.5 in the environment.yaml file, function remains restored to ```ymp stage list```. 

To try to figure out what might be allowing ```ymp stage list``` to work while ```ymp make``` still fails, I ran a diff of the ```conda list``` from the environment that I changed snakemake to 5.2.2 and back to 5.4.5 and an environment that never saw that change. Here that is below: 

```
[hannah@rgnt1-24-235-dhcp Downloads]$ diff remote_conda_list_ymp.txt local_conda_list_ymp.txt 
1c1
< # packages in environment at /data/hollandh/anaconda2/envs/ymp: # ymp stage list works here
---
> # packages in environment at /home/hannah/Software/miniconda2/envs/ymp: # ymp stage list does not work here
11c11
< blas                      2.6                    openblas    conda-forge
---
> blas                      2.7                    openblas    conda-forge
47,48c47,48
< libblas                   3.8.0                6_openblas    conda-forge
< libcblas                  3.8.0                6_openblas    conda-forge
---
> libblas                   3.8.0                7_openblas    conda-forge
> libcblas                  3.8.0                7_openblas    conda-forge
53,54c53,54
< liblapack                 3.8.0                6_openblas    conda-forge
< liblapacke                3.8.0                6_openblas    conda-forge
---
> liblapack                 3.8.0                7_openblas    conda-forge
> liblapacke                3.8.0                7_openblas    conda-forge
77c77
< psutil                    5.6.1            py36h14c3975_0    conda-forge
---
> psutil                    5.6.2            py36h516909a_0    conda-forge
84c84
< pyrsistent                0.14.11          py36h14c3975_0    conda-forge
---
> pyrsistent                0.15.1           py36h516909a_0    conda-forge
```
Hopefully this can help you with the troubleshooting. :)

**Comment by epruesse** [comment]
I need to verify the version of `snakemake` at startup. You need the most recent version in the environment in which you've got ymp.

**Comment by hhollandmoritz** [comment]
Thanks! Is the most recent version higher than 5.4.5?

**Comment by epruesse** [comment]
No, that sounds like the max. If you have that, then I probably need to fix some more stuff.

**Comment by epruesse** [comment]
Basically, YMP messes with internal snakemake API. So it breaks when things change. In this case, it was at least the new `checkpoints` feature. That's the 4 vs 5 arguments in `add_rule`.

**Comment by epruesse** [comment]
I'll have a look at it tomorrow. Need to get things working with 5.4.5 and make some kind of release that allows testing with a specific version of ymp/snakemake

**Comment by hhollandmoritz** [comment]
Got it. ymp installed with snakemake 5.4.5. originally, so the latest version is being installed out of the box, the only problem is the add_rule error.  I only changed to the lower versions to try to see if snakemake was involved in the problem. 

Sounds great! Thanks! Happy to test new versions on my system when you get around to it.

**Comment by epruesse** [comment]
Alright. It should work again. Tests are passing, docs are building. Closing this one, open a new one or email me if (when...) you run into the next thing
